USE [master]
GO

/****** Object:  Database [AFT]    Script Date: 08/04/2012 07:16:34 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'AFT')
DROP DATABASE [AFT]
GO

USE [master]
GO

/****** Object:  Database [AFT]    Script Date: 08/04/2012 07:16:34 ******/
CREATE DATABASE [AFT] ON  PRIMARY 
( NAME = N'AFT', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\AFT.mdf' , SIZE = 1085440KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AFT_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\AFT_log.ldf' , SIZE = 1008000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AFT] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AFT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AFT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AFT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AFT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AFT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AFT] SET ARITHABORT OFF 
GO

ALTER DATABASE [AFT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AFT] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AFT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AFT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AFT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AFT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AFT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AFT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AFT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AFT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AFT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AFT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AFT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AFT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AFT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AFT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AFT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AFT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AFT] SET  READ_WRITE 
GO

ALTER DATABASE [AFT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AFT] SET  MULTI_USER 
GO

ALTER DATABASE [AFT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AFT] SET DB_CHAINING OFF 
GO


